// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AreaSelectionController from "./area_selection_controller"
application.register("area-selection", AreaSelectionController)

import AvatarPreviewController from "./avatar_preview_controller"
application.register("avatar-preview", AvatarPreviewController)

import CafeSelectionController from "./cafe_selection_controller"
application.register("cafe-selection", CafeSelectionController)

import DestructiveConfirmationController from "./destructive_confirmation_controller"
application.register("destructive-confirmation", DestructiveConfirmationController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import TagSelectionController from "./tag_selection_controller"
application.register("tag-selection", TagSelectionController)

import UserMenuController from "./user_menu_controller"
application.register("user-menu", UserMenuController)
