// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AreaSelectionController from "./area_selection_controller"
application.register("area-selection", AreaSelectionController)

import CafeSelectionController from "./cafe_selection_controller"
application.register("cafe-selection", CafeSelectionController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import TagSelectionController from "./tag_selection_controller"
application.register("tag-selection", TagSelectionController)
